# User config
author: "Wheatfield Run"
tagline: "A Prairie-born Netlabel"
description: "A netlabel and a collection of albums maintained by prairie-born people."
keywords: "Wheatfield Run, music, netlabel"
email: "hi@wheatfield.run"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

collections_dir: content
collections:
  artists:
    output: true
  releases:
    output: true